// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5S9TiwrmriW_nr7XGA2vfjX6vLTz05ME',
    appId: '1:1002207489149:web:654183512de50ba00f1514',
    messagingSenderId: '1002207489149',
    projectId: 'fmobile-2a919',
    authDomain: 'fmobile-2a919.firebaseapp.com',
    storageBucket: 'fmobile-2a919.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrC013fYyuRfVaVKMONmQ8hbNb2bt7kjo',
    appId: '1:1002207489149:android:260053c9c8de2d600f1514',
    messagingSenderId: '1002207489149',
    projectId: 'fmobile-2a919',
    storageBucket: 'fmobile-2a919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsciWsgsvxq1bVAgnyz1Fm5cDyHytGL_k',
    appId: '1:1002207489149:ios:e337aa4646e91ee40f1514',
    messagingSenderId: '1002207489149',
    projectId: 'fmobile-2a919',
    storageBucket: 'fmobile-2a919.appspot.com',
    iosBundleId: 'com.example.fmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsciWsgsvxq1bVAgnyz1Fm5cDyHytGL_k',
    appId: '1:1002207489149:ios:e337aa4646e91ee40f1514',
    messagingSenderId: '1002207489149',
    projectId: 'fmobile-2a919',
    storageBucket: 'fmobile-2a919.appspot.com',
    iosBundleId: 'com.example.fmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5S9TiwrmriW_nr7XGA2vfjX6vLTz05ME',
    appId: '1:1002207489149:web:ae17b0703072a2330f1514',
    messagingSenderId: '1002207489149',
    projectId: 'fmobile-2a919',
    authDomain: 'fmobile-2a919.firebaseapp.com',
    storageBucket: 'fmobile-2a919.appspot.com',
  );
}
